// =============================================================================
// ForgeMind API — Local Deterministic LLM Provider (Fallback)
// =============================================================================

import type { LLMProvider } from './types.js';

/**
 * Deterministic local LLM provider for testing and offline execution.
 * Synthesizes structured answers from retrieved codebase snippets without external API keys.
 */
export class LocalDeterministicLLMProvider implements LLMProvider {
  readonly name = 'local-deterministic';

  async generateAnswer(systemPrompt: string, userPrompt: string): Promise<string> {
    // Extract source block headers from system prompt if present
    const sourceHeaderMatches = [
      ...systemPrompt.matchAll(/\[SOURCE \d+\] File: ([^\n]+) \(Lines (\d+)-(\d+)\)/g),
    ];

    const sourcesFound = sourceHeaderMatches.map((m) => ({
      filePath: m[1] || 'Unknown File',
      startLine: m[2] || '1',
      endLine: m[3] || '1',
    }));

    if (sourcesFound.length === 0) {
      return `Based on the indexed codebase, no directly relevant code snippets were found matching your query: "${userPrompt}". Please verify that repository analysis has completed.`;
    }

    const primarySource = sourcesFound[0];
    const uniqueFiles = Array.from(new Set(sourcesFound.map((s) => s.filePath)));

    let answer = `Based on the repository context analysis, here is what was found regarding your question:\n\n`;

    answer += `### Key Implementation Locations\n\n`;
    uniqueFiles.forEach((file) => {
      const fileSources = sourcesFound.filter((s) => s.filePath === file);
      const lineRanges = fileSources.map((s) => `L${s.startLine}–L${s.endLine}`).join(', ');
      answer += `- \`${file}\` (${lineRanges})\n`;
    });

    answer += `\n### Summary Analysis\n`;
    answer += `The functionality related to **"${userPrompt}"** is centered in \`${primarySource?.filePath}\`. `;
    answer += `The retrieved codebase context contains relevant definitions and structural logic in the highlighted line ranges above.\n\n`;
    answer += `> *Generated by ForgeMind Local Intelligence Engine (Offline Mode).*`;

    return answer;
  }
}
